INSERT INTO make(name, country, description) VALUES ('BMW', 'Germany', 'Bayerische Motoren Werke')
INSERT INTO make(name, country, description) VALUES ('Ford', 'USA', 'Ford Motor Company')
INSERT INTO make(name, country) VALUES ('Nissan', 'Japan')
INSERT INTO make(name, country) VALUES ('Opel', 'Germany')
INSERT INTO make(name, country, description) VALUES ('Volvo', 'Sweden', 'Aktiebolaget Volvo')

INSERT INTO engine(type, capacity, horsepower) VALUES ('petrol', 2000, 125)
INSERT INTO engine(type, capacity, horsepower) VALUES ('diesel', 2500, 220)
INSERT INTO engine(type, capacity, horsepower) VALUES ('lpg', 2000, 180)
INSERT INTO engine(type, capacity, horsepower) VALUES ('petrol', 3000, 340)
INSERT INTO engine(type, capacity, horsepower) VALUES ('diesel', 2000, 110)